// Sample menu data for testing purpose
export interface MenuItem {
  _id: string
  name: string
  description: string
  price: number
  category: string
  image: string | null
  isVeg: boolean
  isSpicy: boolean
  prepTime: number
  rating: number
  isAvailable: boolean
  canteenName: string
  canteenId: string
}

// 2. Export the array with all your actual images!
export const demoMenuItems: MenuItem[] = [
  {
    _id: "Demo-m1",
    name: "Veg Thali",
    description: "Complete meal with rice, dal, paneer curry, roti, and salad.",
    price: 120,
    category: "Main Course",
    image: "/veg-thali.jpg",
    isVeg: true,
    isSpicy: false,
    prepTime: 15,
    rating: 4.5,
    isAvailable: true,
    canteenName: "Campus Cafe",
    canteenId: "canteen-1",
  },
  {
    _id: "Demo-m2",
    name: "Masala Dosa",
    description: "Crispy South Indian dosa served with fresh coconut chutney and sambar.",
    price: 90,
    category: "South Indian",
    image: "/masala-dosa.jpg",
    isVeg: true,
    isSpicy: true,
    prepTime: 10,
    rating: 4.6,
    isAvailable: true,
    canteenName: "South Corner",
    canteenId: "canteen-2",
  },
  {
    _id: "Demo-m3",
    name: "Veg Fried Rice",
    description: "Classic Indo-Chinese wok-tossed rice with fresh vegetables.",
    price: 110,
    category: "Chinese",
    image: "/fried-rice.jpg",
    isVeg: true,
    isSpicy: true,
    prepTime: 12,
    rating: 4.3,
    isAvailable: true,
    canteenName: "Wok & Roll",
    canteenId: "canteen-3",
  },
  {
    _id: "Demo-m4",
    name: "Grilled Sandwich",
    description: "Bombay style grilled veg sandwich with green chutney and cheese.",
    price: 70,
    category: "Snacks",
    image: "/sandwich.jpg",
    isVeg: true,
    isSpicy: false,
    prepTime: 8,
    rating: 4.4,
    isAvailable: true,
    canteenName: "Bite Station",
    canteenId: "canteen-4",
  },
  {
    _id: "Demo-m5",
    name: "Classic Burger",
    description: "Aloo tikki patty with fresh lettuce, tomatoes, and house mayo.",
    price: 85,
    category: "Fast Food",
    image: "/burger.jpg",
    isVeg: true,
    isSpicy: false,
    prepTime: 10,
    rating: 4.2,
    isAvailable: true,
    canteenName: "Bite Station",
    canteenId: "canteen-4",
  },
  {
    _id: "Demo-m6",
    name: "Mumbai Pav Bhaji",
    description: "Spicy mashed vegetable curry served with buttery toasted pav buns.",
    price: 95,
    category: "Street Food",
    image: "/pavbhaji.jpg",
    isVeg: true,
    isSpicy: true,
    prepTime: 10,
    rating: 4.7,
    isAvailable: true,
    canteenName: "Campus Cafe",
    canteenId: "canteen-1",
  },
  {
    _id: "Demo-m7",
    name: "Punjabi Samosa",
    description: "Two crispy pastry shells stuffed with spiced potatoes and peas.",
    price: 30,
    category: "Snacks",
    image: "/samosa.jpg",
    isVeg: true,
    isSpicy: true,
    prepTime: 5,
    rating: 4.8,
    isAvailable: true,
    canteenName: "Campus Cafe",
    canteenId: "canteen-1",
  },
  {
    _id: "Demo-m8",
    name: "Hakka Noodles",
    description: "Stir-fried noodles with crunchy cabbage, carrots, and soy sauce.",
    price: 100,
    category: "Chinese",
    image: "/noodles.jpg",
    isVeg: true,
    isSpicy: true,
    prepTime: 12,
    rating: 4.4,
    isAvailable: true,
    canteenName: "Wok & Roll",
    canteenId: "canteen-3",
  },
  {
    _id: "Demo-m9",
    name: "Margherita Pizza",
    description: "Classic personal pan pizza with rich tomato sauce and mozzarella.",
    price: 150,
    category: "Fast Food",
    image: "/pizza.jpg",
    isVeg: true,
    isSpicy: false,
    prepTime: 18,
    rating: 4.5,
    isAvailable: true,
    canteenName: "Bite Station",
    canteenId: "canteen-4",
  },
  {
    _id: "Demo-m10",
    name: "Steamed Idli",
    description: "Soft and fluffy rice cakes served with sambar and coconut chutney.",
    price: 50,
    category: "South Indian",
    image: "/idli.jpg",
    isVeg: true,
    isSpicy: false,
    prepTime: 5,
    rating: 4.6,
    isAvailable: true,
    canteenName: "South Corner",
    canteenId: "canteen-2",
  },
  {
    _id: "Demo-m11",
    name: "Mutter Paneer",
    description: "Cottage cheese and green peas in a rich, creamy tomato gravy. Served with 2 Rotis.",
    price: 140,
    category: "Main Course",
    image: "/mutter-paneer.jpg",
    isVeg: true,
    isSpicy: true,
    prepTime: 15,
    rating: 4.7,
    isAvailable: true,
    canteenName: "Campus Cafe",
    canteenId: "canteen-1",
  },
  {
    _id: "Demo-m12",
    name: "Street Style Vada Pav",
    description: "The iconic Mumbai snack: spicy potato fritter in a soft bun.",
    price: 25,
    category: "Street Food",
    image: "/vada-pav.jpg",
    isVeg: true,
    isSpicy: true,
    prepTime: 5,
    rating: 4.9,
    isAvailable: true,
    canteenName: "Campus Cafe",
    canteenId: "canteen-1",
  },
  {
    _id: "Demo-m13",
    name: "Kanda Poha",
    description: "Light and healthy flattened rice cooked with onions, peanuts, and turmeric.",
    price: 45,
    category: "Breakfast",
    image: "/poha.jpg",
    isVeg: true,
    isSpicy: false,
    prepTime: 5,
    rating: 4.3,
    isAvailable: true,
    canteenName: "Campus Cafe",
    canteenId: "canteen-1",
  },
  {
    _id: "Demo-m14",
    name: "Belgian Waffles",
    description: "Crispy waffles topped with chocolate syrup and powdered sugar.",
    price: 110,
    category: "Desserts",
    image: "/waffles.jpg",
    isVeg: true,
    isSpicy: false,
    prepTime: 12,
    rating: 4.6,
    isAvailable: true,
    canteenName: "Sweet Cravings",
    canteenId: "canteen-5",
  },
  {
    _id: "Demo-m15",
    name: "Cold Drinks",
    description: "Chilled assorted carbonated beverages (Cola, Sprite, Thums Up).",
    price: 40,
    category: "Beverages",
    image: "/colddrinks.jpg",
    isVeg: true,
    isSpicy: false,
    prepTime: 2,
    rating: 4.0,
    isAvailable: true,
    canteenName: "Bite Station",
    canteenId: "canteen-4",
  },
  {
    _id: "Demo-m16",
    name: "Thick Chocolate Milkshake",
    description: "Rich and creamy chocolate milkshake blended with vanilla ice cream.",
    price: 80,
    category: "Beverages",
    image: "/milkshake.jpg",
    isVeg: true,
    isSpicy: false,
    prepTime: 5,
    rating: 4.5,
    isAvailable: true,
    canteenName: "Sweet Cravings",
    canteenId: "canteen-5",
  },
  {
    _id: "Demo-m17",
    name: "Whey Protein Shake",
    description: "Post-workout chocolate protein shake with almond milk.",
    price: 90,
    category: "Beverages",
    image: "/protein-shake.jpg",
    isVeg: true,
    isSpicy: false,
    prepTime: 5,
    rating: 4.8,
    isAvailable: true,
    canteenName: "Sweet Cravings",
    canteenId: "canteen-5",
  },
  {
    _id: "Demo-m18",
    name: "Paneer Roll",
    description: "Delicious paneer wrapped in a soft paratha.",
    price: 85,
    category: "Vegetarian",
    image: "/paneer-roll.jpg",
    isVeg: true,
    isSpicy: false,
    prepTime: 5,
    rating: 4.8,
    isAvailable: true,
    canteenName: "Snacks",
    canteenId: "canteen-5",
  },
 {
    _id: "Demo-m19",
    name: "Cold Coffee",
    description: "Chilled coffee served over ice.",
    price: 70,
    category: "Beverages",
    image: "/cold-coffee.jpg",
    isVeg: true,
    isSpicy: false,
    prepTime: 5,
    rating: 4.8,
    isAvailable: true,
    canteenName: "Sweet Cravings",
    canteenId: "canteen-5",
  }
];

// Optional: You can keep your localStorage loader here if you are using it!
export const loadSampleMenuData = () => {
  const existingData = localStorage.getItem('canteenMenuItems');
  if (!existingData || JSON.parse(existingData).length === 0) {
    localStorage.setItem('canteenMenuItems', JSON.stringify(demoMenuItems));
    return true; 
  }
  return false; 
};